#-----------LOCAL COMPOSE-----------
services:
  bot:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./daily.log:/app/daily.log

#-----------REMOTE COMPOSE-----------
#services:
#  telegram-bot:
#    image: HUB_USERNAME/HUB_IMAGE:latest
#    container_name: telegram-bot
#    restart: always
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./daily.log:daily.log
#      - .env:/app/.env